name: Build iOS IPA

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build
        run: |
          # 显示当前 pubspec.yaml 内容
          echo "Current pubspec.yaml content:"
          cat pubspec.yaml

          # 使用 perl 替换项目名称
          perl -pi -e 's/name: flutter-chatbot/name: flutter_chatbot/' pubspec.yaml

          # 确认修改
          echo "Modified pubspec.yaml content:"
          cat pubspec.yaml

          flutter pub get
          flutter create . --platforms=ios
          cd ios
          rm -rf Pods Podfile.lock
          pod install
          cd ..
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app-ios.ipa Payload/

      - name: ChangeLog
        id: changelog
        run: |
          echo "latest<<EOF" >> $GITHUB_OUTPUT
          awk '/^[0-9]/{i++}i==1' CHANGELOG | sed '${/^$/d}' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/ios/iphoneos/app-ios.ipa
          body: ${{ steps.changelog.outputs.latest }}
